name: Output Info
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps: 
      - name: Run Python Script
        run: |
          python -c '
          def func(x, y):
              res = x + y
              return res
          x = 6
          y = 7
          result = func(x, y)
          print("Result:", result)'
      - name: Script Completed
        run: echo "Done"
