name: Output Info
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps: 
      - name: Run Python Script
        run: python app.py
      - name: Script Completed
        run: echo "Done"
