name: Output Info
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps: 
      - name: python func
        run: |
          def func(x, y):
            return (x + y)
          x = 6
          y = 7
          func(x, y)
      - name: script completed
        run: print("Done")

