name: Test React Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Pull Code
      uses: actions/checkout@v3
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: install dependencies
      run: npm install
    - name: Run Tests
      run: npm test
